# Generated by AI assistant - review and adjust if needed
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_alter_comment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_agency', models.CharField(blank=True, max_length=120)),
                ('referrer_name', models.CharField(max_length=120)),
                ('referrer_email', models.EmailField(max_length=254)),
                ('referrer_phone', models.CharField(blank=True, max_length=40)),
                ('preferred_contact_times', models.CharField(blank=True, max_length=120)),
                ('primary_carer_name', models.CharField(max_length=120, verbose_name='Parent/Carer name')),
                ('address_line1', models.CharField(max_length=160)),
                ('address_line2', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(default='Glasgow', max_length=80)),
                ('postcode', models.CharField(max_length=10)),
                ('interpreter_required', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(blank=True, max_length=80)),
                ('is_rereferral', models.BooleanField(default=False)),
                ('last_support_when', models.CharField(blank=True, help_text='Month/Year is fine (e.g. 05/2023)', max_length=20)),
                ('srv_family_support', models.BooleanField(default=False)),
                ('srv_respite_sitting', models.BooleanField(default=False)),
                ('srv_respite_care', models.BooleanField(default=False)),
                ('srv_geezachance', models.BooleanField(default=False)),
                ('srv_kinship_care', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, verbose_name='Brief reason for referral / goals')),
                ('hscp_locality', models.CharField(choices=[('NE', 'North East'), ('NW', 'North West'), ('S', 'South')], max_length=2, verbose_name='HSCP locality')),
                ('ward', models.IntegerField(choices=[(1, 'Linn'), (2, 'Newlands/Auldburn'), (3, 'Greater Pollok'), (4, 'Cardonald'), (5, 'Govan'), (6, 'Pollokshields'), (7, 'Langside'), (8, 'Southside Central'), (9, 'Calton'), (10, 'Anderston/City/Yorkhill'), (11, 'Hillhead'), (12, 'Victoria Park'), (13, 'Garscadden/Scotstounhill'), (14, 'Drumchapel/Anniesland'), (15, 'Maryhill'), (16, 'Canal'), (17, 'Springburn/Robroyston'), (18, 'East Centre'), (19, 'Shettleston'), (20, 'Baillieston'), (21, 'North East'), (22, 'Dennistoun'), (23, 'Partick East/Kelvindale')])),
                ('neighbourhood', models.CharField(blank=True, max_length=120)),
                ('consent_privacy', models.BooleanField(default=False, help_text="I agree to Geeza Break's privacy notice.")),
                ('consent_media', models.BooleanField(default=False, help_text='I consent to photos being taken and used for Geeza Break marketing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
