# Generated by Django 4.2.8 on 2025-08-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Child name')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('relationship', models.CharField(choices=[('son', 'Son'), ('daughter', 'Daughter'), ('stepchild', 'Step-child'), ('foster', 'Foster child'), ('other', 'Other')], max_length=16)),
                ('has_asn', models.BooleanField(default=False, verbose_name='Additional support needs / disability')),
                ('school_nursery', models.CharField(blank=True, max_length=160, verbose_name='School/Nursery (optional)')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.referral')),
            ],
            options={
                'ordering': ['dob', 'full_name'],
            },
        ),
    ]
