# Generated by Django 4.2.8 on 2025-08-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_referralchild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=140)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='criteria_other',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='referral',
            name='criteria',
            field=models.ManyToManyField(blank=True, related_name='referrals', to='main.criterion'),
        ),
    ]
