# Generated by Django 4.2.8 on 2025-08-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_criterion_referral_criteria_other_referral_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Flag indicating if notification email was sent'),
        ),
    ]
