# Generated by Django 4.2.8 on 2025-08-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_referral_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_title', models.CharField(max_length=100)),
                ('joined_date', models.CharField(help_text='When you came on board as a trustee', max_length=100)),
                ('reason_for_joining', models.TextField(help_text='Why you got involved in supporting Geeza Break')),
                ('role_description', models.TextField(help_text='What your role entails')),
                ('favorite_aspect', models.TextField(help_text='What you like best about being a Geeza Break Trustee')),
                ('fun_fact', models.TextField(help_text="Fun fact/what you like to do 'for a break' when you have the chance")),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_members/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the page')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
