# Generated by Django 4.2.8 on 2025-08-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image_path',
            field=models.CharField(blank=True, help_text="Path to image in static folder (e.g. 'images/staff/1t.jpg')", max_length=255),
        ),
    ]
