# Generated by GitHub Copilot on 2025-08-27
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0009_teammember_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='joint_visit_required',
            field=models.BooleanField(default=False, help_text='Tick if a joint visit with another professional is required.'),
        ),
    ]
