# Generated by Django 4.2.24 on 2025-09-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_teammember_image_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "roles",
                    models.CharField(
                        help_text="Comma-separated role keys from ROLE_CHOICES",
                        max_length=200,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        blank=True, help_text="e.g., weekdays, evenings", max_length=200
                    ),
                ),
                ("is_student", models.BooleanField(default=False)),
                ("course_or_discipline", models.CharField(blank=True, max_length=160)),
                ("message", models.TextField(blank=True)),
                ("consent_contact", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
