# Generated by Django 4.2.24 on 2025-09-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_volunteerinterest'),
        ('main', '0011_add_new_criteria'),
    ]

    operations = [
    ]
